export const deskCopy = {
  en: {
    home: "Your Live Desk", intro: "Connect a platform, import products, then start a live rehearsal.",
    start: "Start", desk: "Live Desk", connect: "Connect", connected: "Connected (SIMULATED)", disconnected: "Not connected",
    import: "Import products", sample: "Use sample pack", paste: "Paste CSV or TSV", importText: "Import pasted products",
    importHelp: "Use a header row and the product fields from your export. Missing prices stay missing.",
    connectFirst: "Connect the simulated platform before importing.", pasteFirst: "Paste product rows to import.",
    startLive: "Start live", startFailed: "Live did not start. Check platform status and try again.",
    next: "Next step", nextConnect: "Connect the simulated platform", nextImport: "Import your products", nextStart: "Start a live rehearsal",
    products: "Products", stock: "Stock", missing: "Not entered", synced: "Synced (SIMULATED)", queued: "Queued (SIMULATED)", failed: "Failed (SIMULATED)",
    remove: "Remove", showing: "Showing (SIMULATED)", pin: "Pin", unpin: "Unpin", unpinBasis: "Unpin is guessed, no Shopee page found.",
    run: "Run", pause: "Pause", speed: "Clock speed", reset: "Reset", skip30: "+30 s", skip60: "+1 min", skip300: "+5 min",
    clock: "Virtual clock", elapsed: "Elapsed", live: "Live", ended: "Ended", idle: "Not started", end: "End live",
    viewers: "Viewers", noViewers: "Not simulated", viewersChart: "Viewers over time", cartChart: "Add to cart per minute",
    markers: "Markers show when you acted, not what caused a change", chartDetails: "Chart values and markers", noPoints: "No chart data yet",
    comments: "Comments", window: "Last 2 minutes", noComments: "No comments yet", masked: "PII masked",
    ask_price: "Ask price", ask_size: "Ask size", ready_to_buy: "Ready to buy", praise: "Praise", other: "Other",
    copilot: "Copilot", signals: "Signals suggest; they do not establish cause.", sampleSize: "Sample size", confidence: "Confidence", source: "Source",
    rules: "Rules", ai: "AI", proposed: "Proposed", accepted: "Accepted", dismissed: "Dismissed", performed: "Performed",
    low: "Low", medium: "Medium", high: "High", accept: "Accept", dismiss: "Dismiss", noSuggestions: "No suggestions yet",
    lifecycle: "Accepting records your choice. Performed requires the platform to show the pin.",
    phone: "Host phone preview", phoneHelp: "Read-only audience preview. Use the desk controls to act.",
    assumptions: "Simulation assumptions", fingerprint: "Run fingerprint", noFingerprint: "No events yet",
    wire: "Wire log", noWire: "No wire log is available for this rehearsal.",
    unknown: "Live not found", unknownHelp: "This browser has no live with that id. Start a rehearsal first.",
    legacy: "Legacy", legacyIntro: "The original planning screens keep their existing URLs.",
    sessions: "Sessions", sessionsHelp: "Browse the original planned, active and ended shows.",
    library: "Products", libraryHelp: "Browse the original product library.",
    insights: "Insights", insightsHelp: "Review recorded evidence from the original shows.",
    simulator: "Simulator", simulatorHelp: "Rehearse the original run-of-show scenarios (SIMULATED).",
    integrations: "Integrations", integrationsHelp: "See platform capabilities and their evidence basis.",
    create: "Create", createHelp: "Set up an original show with a planned run of show.",
  },
  vi: {
    home: "Bàn điều hành Live", intro: "Kết nối nền tảng, nhập sản phẩm rồi bắt đầu buổi diễn tập live.",
    start: "Bắt đầu", desk: "Bàn điều hành Live", connect: "Kết nối", connected: "Đã kết nối (SIMULATED)", disconnected: "Chưa kết nối",
    import: "Nhập sản phẩm", sample: "Dùng bộ mẫu", paste: "Dán CSV hoặc TSV", importText: "Nhập sản phẩm đã dán",
    importHelp: "Dùng dòng tiêu đề và các trường sản phẩm trong bản xuất. Giá chưa nhập vẫn để trống.",
    connectFirst: "Kết nối nền tảng mô phỏng trước khi nhập.", pasteFirst: "Dán các dòng sản phẩm để nhập.",
    startLive: "Bắt đầu live", startFailed: "Live chưa bắt đầu. Kiểm tra trạng thái nền tảng và thử lại.",
    next: "Bước tiếp theo", nextConnect: "Kết nối nền tảng mô phỏng", nextImport: "Nhập sản phẩm của bạn", nextStart: "Bắt đầu buổi diễn tập live",
    products: "Sản phẩm", stock: "Tồn kho", missing: "Chưa nhập", synced: "Đã đồng bộ (SIMULATED)", queued: "Đang chờ (SIMULATED)", failed: "Lỗi (SIMULATED)",
    remove: "Xóa", showing: "Đang hiển thị (SIMULATED)", pin: "Ghim", unpin: "Bỏ ghim", unpinBasis: "Bỏ ghim là suy đoán, chưa tìm thấy trang Shopee.",
    run: "Chạy", pause: "Tạm dừng", speed: "Tốc độ đồng hồ", reset: "Đặt lại", skip30: "+30 giây", skip60: "+1 phút", skip300: "+5 phút",
    clock: "Đồng hồ ảo", elapsed: "Đã chạy", live: "Đang live", ended: "Đã kết thúc", idle: "Chưa bắt đầu", end: "Kết thúc live",
    viewers: "Người xem", noViewers: "Chưa mô phỏng", viewersChart: "Người xem theo thời gian", cartChart: "Thêm vào giỏ mỗi phút",
    markers: "Dấu mốc cho biết lúc bạn thao tác, không phải nguyên nhân thay đổi", chartDetails: "Giá trị và dấu mốc biểu đồ", noPoints: "Chưa có dữ liệu biểu đồ",
    comments: "Bình luận", window: "2 phút gần nhất", noComments: "Chưa có bình luận", masked: "Đã che thông tin cá nhân",
    ask_price: "Hỏi giá", ask_size: "Hỏi cỡ", ready_to_buy: "Sẵn sàng mua", praise: "Khen", other: "Khác",
    copilot: "Copilot", signals: "Tín hiệu gợi ý, không chứng minh nguyên nhân.", sampleSize: "Cỡ mẫu", confidence: "Độ tin cậy", source: "Nguồn",
    rules: "Quy tắc", ai: "AI", proposed: "Đề xuất", accepted: "Đã chấp nhận", dismissed: "Đã bỏ qua", performed: "Đã thực hiện",
    low: "Thấp", medium: "Vừa", high: "Cao", accept: "Chấp nhận", dismiss: "Bỏ qua", noSuggestions: "Chưa có đề xuất",
    lifecycle: "Chấp nhận ghi lại lựa chọn của bạn. Đã thực hiện cần nền tảng hiển thị sản phẩm được ghim.",
    phone: "Xem trước điện thoại host", phoneHelp: "Chỉ xem giao diện khán giả. Thao tác bằng các nút trên bàn điều hành.",
    assumptions: "Giả định mô phỏng", fingerprint: "Dấu vân tay lượt chạy", noFingerprint: "Chưa có sự kiện",
    wire: "Nhật ký lệnh", noWire: "Chưa có nhật ký lệnh cho buổi diễn tập này.",
    unknown: "Không tìm thấy live", unknownHelp: "Trình duyệt này chưa có live với mã đó. Hãy bắt đầu diễn tập.",
    legacy: "Màn hình cũ", legacyIntro: "Các màn hình lập kế hoạch ban đầu giữ nguyên đường dẫn.",
    sessions: "Buổi live", sessionsHelp: "Xem các buổi đã lên kế hoạch, đang chạy và đã kết thúc ban đầu.",
    library: "Sản phẩm", libraryHelp: "Xem thư viện sản phẩm ban đầu.",
    insights: "Phân tích", insightsHelp: "Xem bằng chứng đã ghi nhận từ các buổi ban đầu.",
    simulator: "Trình mô phỏng", simulatorHelp: "Diễn tập các kịch bản lịch trình ban đầu (SIMULATED).",
    integrations: "Tích hợp", integrationsHelp: "Xem khả năng nền tảng và cơ sở bằng chứng.",
    create: "Tạo", createHelp: "Thiết lập buổi ban đầu với lịch trình dự kiến.",
  },
};

export type DeskCopy = typeof deskCopy.en;
